### ISSUE TITLE
Blog plugin not working...!

### ISSUE THREAD

**Issue by techzamil** [JacksiroKe/q2a-blog-post#13]
Hi, Sir! Your plugin is great.. But it is not working...  I installed this plugin on my sute then my site doesn't run.. Please solve...

**Comment by JacksiroKe** [comment]
Hey @techzamil Kindly give more details because I have a lot of people who are using this plugin. 
Let me know what version of Q2A you are using?
What file is showing on error?
What is the unexpected behavior of the plugin?

**Comment by techzamil** [comment]
Hi,  I'm using the latest 1.8.3 version.. When I upload this plugin my site doesn't work.. Site shows blank page.. And when I remove that, ny site works great

**Comment by techzamil** [comment]
My site is TwiceProshno.com

**Comment by JacksiroKe** [comment]
Well sorry for the inconvenience caused by the plugin. However from your description of the problem let me honest with you I find it hard to diagnose where the problem is. I can't confirm that my plugin is the culprit here.
My Take: From the look of things its appears you may be having other plugins conflicting the whole Q2A system and since the plugins relies so much on that it keeps failing your site.

Kindly check my test site https://qtoa.appsmata.com/blog where you can sign up and and post on my blog.

Now to be able to find out what is the issue try to install a new Q2A site on your localhost following this instruction https://github.com/JacksiroKe/q2a-blog-post/blob/master/INSTALLING.md and see if it works well on your localhost. Then start adding other plugins to it and monitor the behavior of your site.

**Comment by techzamil** [comment]
Oh! The problem was happened because I didn't renamed q2a-blog-post-master to q2a-blog-post..
Thanks for the plugin

**Comment by JacksiroKe** [comment]
you are welcome sir

**Comment by techzamil** [comment]
I have a question? Here the link, (mysite.com/blog/year/month/date) can not be changed to mysite.com/blog/123
Is it change it will be great

**Comment by JacksiroKe** [comment]
Well that is a permium feature buddy
